version:     "00--12-Sep-2022"
copyright:   "2022"
author:      "Tessa Wlodarczak"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/twlodarczak/os222/"
myloglink:   "/TXT/mylog.txt"
mypublickey: ""
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
