version:          "0--12-Sept-2022"
copyright:        "2021-2022"
title:            "twlodarczak GitHub Page"
author:           "Tessa"
address:          ""
description:
  Ttwlodarczk GitHub Page
disclaimer:
  I have spoken.
tagline:          ""
keywords:         ""
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "GitHub"
  link:           "https://github.com/twlodarczak/os222/
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlgithub:        "https://github.com/twlodarczak/os222/"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

